freebsd_instance:
  image_family: freebsd-12-1

freebsd_task:
  env:
    matrix:
      - OCAML_VERSION: 4.08.1
      - OCAML_VERSION: 4.09.1
      - OCAML_VERSION: 4.10.1
      - OCAML_VERSION: 4.11.1
  pkg_install_script: pkg install -y ocaml-opam gmp gmake pkgconf bash
  ocaml_script: opam init -a --comp=$OCAML_VERSION
  dependencies_script: eval `opam env` && opam install -y --deps-only .
  build_script: eval `opam env` && dune build
  watermark_script: eval `opam env` && dune subst
  release_script: eval `opam env` && dune build --profile=release
  package_script: packaging/FreeBSD/create_package.sh
  albatross_artifacts:
    path: _build/albatross*txz
